- hosts: web
  gather_facts: true
  become: true

  tasks:
  - name: Create directory
    file:
      path: /home/ec2-user/testdirAnsible
      state: directory

  - copy:
      src: /root/ansible-tutorials/inventory/ansible-nodes
      dest: /tmp/ansible-nodes

  - name: Get nodes
    shell: cat /tmp/ansible-nodes

  - yum:
      pkg: httpd
      state: installed

  - yum:
      pkg: git
      state: installed

  - git:
      repo: https://github.com/becloudready/prometheus_monitoring.git
      dest: /tmp version=HEAD
