- hosts: node01
  gather_facts: false

  tasks:

  - name: Install multiple packages
    yum:
      pkg: "{{ item }}"
      state: present
    with_items:
    - mlocate
    - strace
    - java-1.8.0-openjdk
    - php

  - name: Create Directories
    file:
      path: "/home/ec2-user/{{ item }}"
      state: directory
    with_items:
    - yelp
    - google
    - apple
    - yahoo
    - allstate
